source 'https://rubygems.org'
group :development, :test do
  gem 'axinite', path: '..'
end
gem 'active_force', path: ENV.fetch('ACTIVE_FORCE_PATH')
gem 'rspec', '~> 3.13.0'
gem 'rake', '~> 13.0'
gem 'webmock', '~> 3.26.0'
version = ENV['LEGACY'] == '1' ? '7.0.10' : '8.1.3.1'
%w[railties actionpack activejob activesupport activemodel].each { |name| gem name, version }
gem 'restforce', ENV['LEGACY'] == '1' ? '5.3.1' : '8.0.1'
# Restforce passes JSON parser options as a positional hash (removed in JSON 3).
gem 'json', '< 3'
