source 'https://rubygems.org'
gemspec path: '..'
gem 'active_force', path: ENV.fetch('ACTIVE_FORCE_PATH')
gem 'rspec', '~> 3.13.0'
gem 'rake', '~> 13.0'
if ENV['LEGACY'] == '1'
  gem 'activesupport', '~> 7.0.0'
  gem 'activemodel', '~> 7.0.0'
  gem 'restforce', '~> 5.3.1'
else
  gem 'activesupport', '~> 8.1.0'
  gem 'activemodel', '~> 8.1.0'
  gem 'restforce', '~> 8.0'
end
